env:
  global:
  - AWS_REGION=eu-west-1
  - STATE_BUCKET=jcf-tf-state
  - BLUE_STATE_KEY=demotiad/frontblue
  - GREEN_STATE_KEY=demotiad/frontgreen
  - APP_DIR=app/vote
  - REPO_NAME=demotiad/vote
  - WEBSITE=summit.awsdemo.d2-si.eu
  - TERRAFORM_VERSION=0.10.7
  - TOOLS_DIR=$HOME/tools
  - TERRAFORM_DIR=terraform/app/frontends
  - secure: CkD4r2YKTMCEpqYnhsR1JxLmskplBpwsEwUAAvR4ruD/ixtf8e6FrMHuXdjhukz/YGtvg4uUL0/ZAe9U6k4IX3VK9jEsu6DtCWSzUPCRXF4hFkn+5uvR0yU45PLt4d8VkgK/z9yeza+kwCupNEv+t8GcVAku9xSfaqR9K+bVtLcpTfspa8n6xeznlwCjVi/NuWOgEH1J5YU26IiU7nQK4uaZrXINXwkvz9ivasXPSl23fieRCky+Xjt3oFw3IBxJMex4O8iVOAfQYKH/Ii9xNKptdtSihu7IKBHGXE4mccQu4o1pP+Q6hMtFV1CA81i38RSwz0U5YZQonAYRgXytjJgC6M1h6onVKJFXXTaSAKxwNH+00PQtJyxQoiqxwgHBwrU1QkOWCEnCNTss81hAGNqg9APnherU2Bl8UjwXsmqcZ9ikiih/IWqXtC3nSiXOf3KrJg9WrbdmnlU6YmxAeMuTGUPoKH2TKzZQ0W183vh6oUDRhTfVnM7f61tyACAvx7fIC4M2U2Sz4wgHruwBT8gz5N6h2AqQsbIIbIuUIrihnra7rgKpG8StAZgy/1xEx2sTXMwhsC3wKlxDK74muCWZE/gAyCaEYPjCOUj0jGXTeXJ86ZX1M04OVZ4icRwPiHHnO2DOOD1uJcETiDfml5wkuXazc3iwvTLb6IxZbU4=
  - secure: V1gFCqJVcO9jr4sJiawASMnzqbNH9hjDZdcRnHwCQKfYYLfZ9IHP3nx8IdzfHnbDtD5fkfggBPZ3wL8CYxxUngOH+qPuwvkzCwZBLtFGGG8k4Qi2IiLNSFCzbXcO1Docg8ErtLEA0nKYyBeQVQ+yZbcCJpo3o/fGewbUUYwuDFS1+Q+nCIG6FJqPJ06C2s5NSHJ/e+y123ossHBkECLjEZGrhUGVB3qSlDcEYT6lH0oRkGD2Sl3o6PM3iKPQhXsKDl+bZDgZpIZuZUqgat+yHrkjToGI6Exjbr3Bm0Nq1H0vKShh8EYovRvt/TrDhwuJEPF75tzYNVjcNmp4rkBeaxTO+GBiti9UkljnIKZKuCLcP85SB0Udg9M9SuiFJF7QA7XCQchvtVFTmJxZsJaMaLMxY/QQHEIodQUoU7A0bnJhZP4F+IgH3oQmf6GE5gT7Sos4cErrqL63zKmgBTkFrIrbsOtTXdRs1koo45sOJh0VV6LC5DBfsG+o0j5mkZvOtTQWLyVWrmrT0JzF7Ix0HLGewLjMRbuWC2wSgXVjkKpG+LJIZHVvXwwySUldOoXgsuAab2TJYlOlniJqPAlu6vSEtcvqIC+kqf2SifbUd3ylyafO8Dj8papKOYKHExLK5FkCBThElFk96pAxoap/lckXPKfszVw1NNEKqtdQnLA=


sudo: required

language: python

python:
- '2.7'

services:
- docker

script:
- export COMMIT_SUBJECT="$(git log --format=%s --no-merges -n 1)"

before_deploy:
- export PATH=$PATH:$TOOLS_DIR/bin
- scripts/install_terraform.sh
- pip install awscli

deploy:
  provider: script
  script:
  - scripts/build_push_update.sh
  on:
    branch: master
    condition: $COMMIT_SUBJECT != *"[no deploy]"*
