env:
  global:
  - AWS_REGION=eu-west-1
  - STATE_BUCKET=jcf-tf-state
  - BLUE_STATE_KEY=demotiad/frontblue
  - GREEN_STATE_KEY=demotiad/frontgreen
  - APP_DIR=app/vote
  - REPO_NAME=demotiad/vote
  - WEBSITE=summit.awsdemo.d2-si.eu
  - TERRAFORM_VERSION=0.10.7
  - TOOLS_DIR=$HOME/tools
  - TERRAFORM_DIR=terraform/app/frontends
  - secure: RdX1h81HgMreqh/Md/soBbkUET1faIuCADhoGFS2N3/2Q6cplYny6rTy9qVoWF9XH/0YSYuqZuPuPpqP1SsH/h0LIHDHOJoMs4sdRwiUEzenda4QvOcaJxIrFVGrV4wKvxJp0B05cX8mwHJF9/pFEfVOhDQ12KhqtEw+UioD+0LXj3kzDIDs4ZGg704n9ouhVjEZ/OXFO3v1t2tSit327ZBv0PEqB8NBGNIlskG4FUihl04rpAE9VnUX2s+/73n7mlNtVYzXqQ9KPU4/074EjiUIaTphPLmx3ETlDaGcB38GT3Q7zigCC3y+vEWlOoajRxaWkRZEqUx8Scmew+EButsxjVCQcdElfoZWUoZXb97Scr5ewoFZ/VzMnRvig5HW1QWkZ3weaHh41ftwmV2jG2jr+mQ1frycOyRnJD3q3+MJ51rVrtDpvgFnQELQPBNoXMHdham98u9gk3icXDFAyIbQ3UkvtDVx1E8urOLLVaOjPI48gofpsoR0I5Go3kWdRA0UAXn8YLYYKBAD+s/TKJlDp4lKVKaE0FHY0iqvzjgAD1aqyjk4yB6do88hXZfSa7s3bjA1LFG102e5e1ThGnIoybLiwWyc6WsrRpYoX/h3dXOvUZLEJU3ijeAKU9g/mlOe06LpMuG3LeVsRkXeZMSKFeIKFiug8XR0g320d88=
  - secure: mqPZfsa0AzlFLXGdEsfbkcoRVk6UyGqOvqNkIHN0n63BBjvxZKh3KDndQWYsh56yIipoREQVG0WTqsTYQyOOmp6zKsLtCg9YP+wQy1Nq1tV/5YMorfOW9ljmT4T5gLryZOjSZ3PATTK2MpvsfLIrAfrEstP1KtucbMK471SPb6ZXau/o3TnsqiWDbW60YBhDDKtLq5W2Kg+cHSt1cVOrAkA7v2ERFwTFyKhBEJe+HnTj2VT4P+Asx81PTIr3BFK4gMlrOnAe07XLVodI5X7J/5QjN6HrJAjFezZF2RbMa8vtO6FQCgobuM39vdfdauHKtvcTWefYr96MwTNzrSnqb9ORUVwTE7e6j9ijFEooHBp0q6z8IcwzENG1Gipw043/DG33lafW17jNlw9MIvXBn3wKTHRKI4EAbbGPjR0swnLQacsLdL8DCLXBKJzlrX3Lq2ONBcLC0/FkDtHxkJkceQOqtiKTOl8TM1kqJgl0viwRsh3K4Q7LR82ADw+6b4XurpXjml/UQrdK4xX+udIXciYvmxOortX3JlHK9x7Aw8VqpRdoPp5HfTjjbYrjoNut2dKpA5Sbz5GlY3dOKR3EKDrZLz/VKQTazQuRcA8riqdc3zJdmNapmkfcXakTVpf0iDOhmUBBpg/iF2mcJYgivga+WFF+JxGRg+r+vynerl4=

sudo: required

language: python

python:
- '2.7'

services:
- docker

script:
- export COMMIT_SUBJECT="$(git log --format=%s --no-merges -n 1)"

before_deploy:
- export PATH=$PATH:$TOOLS_DIR/bin
- scripts/install_terraform.sh
- pip install awscli

deploy:
  provider: script
  script:
  - scripts/build_push_update.sh
  on:
    branch: master
    condition: $COMMIT_SUBJECT != *"[no deploy]"*
